### ISSUE TITLE
Requirements for uptime_kuma not found: ['pyuptimekuma==0.0.6'].

### ISSUE THREAD

**Issue by Egglestron** [meichthys/uptime_kuma#37] opened 2023-02-23 07:48 UTC
Hi,

Uptime Kuma integration requires dependency pyuptimekuma version 0.0.6, but latest version is 0.0.4 on GitHub. 
Please find attached the logs of my Home Assistant instance, version 2023.3.0 b0.

> Logger: homeassistant.setup
> Source: setup.py:205
> First occurred: February 22, 2023 at 23:32:55 (1 occurrences)
> Last logged: February 22, 2023 at 23:32:55
> 
> Setup failed for custom integration uptime_kuma: Requirements for uptime_kuma not found: ['pyuptimekuma==0.0.6'].

**Comment by meichthys** [comment] 2023-02-23 14:49
I would think that the version of pyuptimekuma should not be coming from github, but rather from pypi which has the 0.0.6 version:
https://pypi.org/project/pyuptimekuma/

**Comment by alexruffell** [comment] 2023-02-23 16:56
@meichthys Can you clarify? I have the same issue and don't know what to do to fix it.

**Comment by meichthys** [comment] 2023-02-23 20:28
@alexruffell and @Egglestron It mayhave something to do with never versions of pip which resolve dependencies differently than in the past. 

The issue here seems to be that we use pyuptimekuma which relies on a newer version of `prometheus-client` than what homeassistant requires (we require anything greater than v0.14.1 while HA requires exactly version 0.7.1)

Since we likely won't get Homeassistant to update their dependency too easily, we may be able to relax our requirement. @jayakornk  Do you know if v0.7.1 would work for pyuptimekuma?

**Comment by Intecpsp** [comment] 2023-03-01 21:13
I did not have this issue until updating to 2023.3 today. I got this same error for other packages as well. I wonder if [this](https://www.home-assistant.io/blog/2023/03/01/release-20233/#python-311-support) broke things. @Egglestron has been, but @alexruffell have you been running beta HA?

**Comment by alexruffell** [comment] 2023-03-01 21:29
@Intecpsp Yes, I was on 2023.3 betas, now stable.

**Comment by henrikbla** [comment] 2023-03-01 22:02
I can confirm this issue happens wirh 2023.03.0 release, thus breaking the integration. Let me know if you need any more details.

**Comment by Heelderpeel** [comment] 2023-03-02 00:19
same problem for me after hassio update 2023.3

**Comment by nosut** [comment] 2023-03-02 04:36
Same issue here as well

```
Logger: homeassistant.setup
Source: setup.py:205
First occurred: 11:33:43 PM (1 occurrences)
Last logged: 11:33:43 PM
Setup failed for custom integration uptime_kuma: Requirements for uptime_kuma not found: ['pyuptimekuma==0.0.6'].
```

**Comment by brandoningli** [comment] 2023-03-02 05:15
Adding yet another instance to the list of affected ones.

Integration v2.0.3 via HACS
HAOS 9.5, Supervisor 2023.01.1
Works on Core 2023.2.5, fails on 2023.3.0 with the above requirements error.

**Comment by danihalter1** [comment] 2023-03-02 07:08
Same issue here, after upgrading to 2023.3.0:

HAOS 9.5
Installed via HACS, version 0.5.2
Works on Core 2023.2.5, but does not load on 2023.3.0, with the requirements error below:

_Logger: homeassistant.setup
Source: setup.py:205
First occurred: 12:54:56 AM (1 occurrences)
Last logged: 12:54:56 AM

Setup failed for custom integration uptime_kuma: Requirements for uptime_kuma not found: ['pyuptimekuma==0.0.6']._

**Comment by derekoharrow** [comment] 2023-03-02 09:12
Same problem here on HA 2023.3.0:

```
Setup failed for custom integration uptime_kuma: Requirements for uptime_kuma not found: ['pyuptimekuma==0.0.6'].

	2023-03-02 09:06:20.150 ERROR (SyncWorker_3) [homeassistant.util.package] Unable to install package pyuptimekuma==0.0.6: ERROR: Cannot install pyuptimekuma==0.0.6 because these package versions have conflicting dependencies.
	ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

	[notice] A new release of pip is available: 23.0 -> 23.0.1
	[notice] To update, run: pip install --upgrade pip
```

**Comment by ghc88uk** [comment] 2023-03-02 11:08
Same issue for me since updating to HA 2023.3.0. Had one other integration refuse to load after updating (AsusRouter) but they have put an update out that has fixed it. Any idea on how to fix the uptime kuma integration or do we need to wait until an update is published?

**Comment by nsleigh** [comment] 2023-03-02 11:42
> Uptime Kuma integration requires dependency pyuptimekuma version 0.0.6, but latest version is 0.0.4 on GitHub. Please find attached the logs of my Home Assistant instance, version 2023.3.0 b0.
Although the release version says 0.0.4 the __init__.py file says it is 0.0.6.

**Comment by bighippo999** [comment] 2023-03-02 12:00
+1 for upgrading to HA 2023.3.0 and googling this error.

**Comment by meichthys** [comment] 2023-03-02 12:06
The version shouldn't be an issue since the correct version is listed in pypi. There is however a package discrepancy with prometheus-client which already exists in homeassistant core (version 0.7.1) while our main dependency pyuptimekuma requires a newer version.

Ideally the prometheus integration of homeassistant core would be updated to a newer version but I don't see that happening too soon so I have submitted a proposed fix to our upstream dependency here https://github.com/jayakornk/pyuptimekuma/pull/3 once that is merged, we should be able to push out an update to fix this.

We may be able to monkey patch our manifest.json to update our requirements but I haven't been able to try it yet.

**Comment by djcrawleravp** [comment] 2023-03-02 14:08
> The version shouldn't be an issue since the correct version is listed in pypi. There is however a package discrepancy with prometheus-client which already exists in homeassistant core (version 0.7.1) while our main dependency pyuptimekuma requires a newer version.
> 
> Ideally the prometheus integration of homeassistant core would be updated to a newer version but I don't see that happening too soon so I have submitted a proposed fix to our upstream dependency here [jayakornk/pyuptimekuma#3](https://github.com/jayakornk/pyuptimekuma/pull/3) once that is merged, we should be able to push out an update to fix this.
> 
> In the mean time we may be able to monkey patch our manifest.json to update our requirements but I haven't been able to try it yet.

I hope this fix the issue, I'll disable the integration in the meantime

**Comment by JGNi** [comment] 2023-03-02 17:58
Yup also here. For now I've disabled Kuma. Hope to see it solved soon

**Comment by danielsmith89** [comment] 2023-03-02 18:05
I've found that doing a 

pip3 install pyuptimekuma==0.0.6

Inside the container fixes it in the interim.

**Comment by djcrawleravp** [comment] 2023-03-02 19:46
> I've found that doing a
> 
> pip3 install pyuptimekuma==0.0.6
> 
> Inside the container fixes it in the interim.

That certainly helped me for the time being, let's hope this issue is fixed soon :D

**Comment by SHHA24** [comment] 2023-03-03 10:50
> 

@danielsmith89 could you give some more details around that please, is that in the docker container, what was the command you ran ? as I tried pip3 install pyuptimekuma==0.0.6
didn't do anything.... 

thanks

**Comment by danielsmith89** [comment] 2023-03-03 10:51
> > 
> 
> @danielsmith89 could you give some more details around that please, is that in the docker container, what was the command you ran ? as I tried pip3 install pyuptimekuma==0.0.6 didn't do anything....
> 
> thanks

Yes, go inside the Home Assistant docker container (if that's what you are running HA in) and the issue that comand

**Comment by taelinn** [comment] 2023-03-03 14:55
> > > 
> > 
> > 
> > @danielsmith89 could you give some more details around that please, is that in the docker container, what was the command you ran ? as I tried pip3 install pyuptimekuma==0.0.6 didn't do anything....
> > thanks
> 
> Yes, go inside the Home Assistant docker container (if that's what you are running HA in) and the issue that comand

Thank you that worked.

**Comment by VNRARA** [comment] 2023-03-04 14:19
> > > > 
> > > 
> > > 
> > > @danielsmith89 could you give some more details around that please, is that in the docker container, what was the command you ran ? as I tried pip3 install pyuptimekuma==0.0.6 didn't do anything....
> > > thanks
> > 
> > 
> > Yes, go inside the Home Assistant docker container (if that's what you are running HA in) and the issue that comand
> 
> Thank you that worked.

I plonked that into the HA terminal (Ha OS via VMM) but it didn't work.

**Comment by VNRARA** [comment] 2023-03-04 16:27
If I change the manifest to 0.0.4 I'm still getting an error. Something else must be going on? 

Logger: homeassistant.util.package
Source: util/package.py:107
First occurred: 17:26:17 (3 occurrences)
Last logged: 17:26:26

Unable to install package pyuptimekuma==0.0.4: ERROR: Could not find a version that satisfies the requirement pyuptimekuma==0.0.4 (from versions: 0.0.1, 0.0.6) ERROR: No matching distribution found for pyuptimekuma==0.0.4 [notice] A new release of pip is available: 23.0 -> 23.0.1 [notice] To update, run: pip install --upgrade pip

**Comment by sandrybridge** [comment] 2023-03-06 08:32
> > > > > 
> > > > 
> > > > 
> > > > @danielsmith89 could you give some more details around that please, is that in the docker container, what was the command you ran ? as I tried pip3 install pyuptimekuma==0.0.6 didn't do anything....
> > > > thanks
> > > 
> > > 
> > > Yes, go inside the Home Assistant docker container (if that's what you are running HA in) and the issue that comand
> > 
> > 
> > Thank you that worked.
> 
> @danielsmith89 I plonked that into the HA terminal (Ha OS via VMM) but it didn't work. It updated, but it didn't work.

The SSH terminal is an addon that runs inside its own container, you have to attach to homassistant docker (if you run "docker ps -a" you should see it running) and then you run the command to install pyuptimekuma... I installed portainer-agent on hassos in a docker so it is much easier to access and manage the dockers environment from outside the addon SSH terminal.

**Comment by phk-r** [comment] 2023-03-06 13:43
Im running HAOS and Uptime Kuma on a Raspberry Pi3 with docker-compose. I jumped inside the container but no go.

```
Collecting pyuptimekuma==0.0.6
  Could not find a version that satisfies the requirement pyuptimekuma==0.0.6 (from versions: )
No matching distribution found for pyuptimekuma==0.0.6
```
Any advice is much appreciated.

**Comment by Sarnog** [comment] 2023-03-06 14:23
> Im running HAOS as a VM and Uptime Kuma on a Raspberry Pi3 with docker-compose. I jumped inside the container but no go.
> 
> ```
> Collecting pyuptimekuma==0.0.6
>   Could not find a version that satisfies the requirement pyuptimekuma==0.0.6 (from versions: )
> No matching distribution found for pyuptimekuma==0.0.6
> ```
> Any advice is much appreciated.
> 
> edit: clarification around my setup

Open portainer --> open homeassistant container --> open console --> typ: pip install --upgrade pip --> restart home assistant OS

**Comment by walkerfreeman** [comment] 2023-03-06 17:18
> > Im running HAOS as a VM and Uptime Kuma on a Raspberry Pi3 with docker-compose. I jumped inside the container but no go.
> > ```
> > Collecting pyuptimekuma==0.0.6
> >   Could not find a version that satisfies the requirement pyuptimekuma==0.0.6 (from versions: )
> > No matching distribution found for pyuptimekuma==0.0.6
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Any advice is much appreciated.
> > edit: clarification around my setup
> 
> Open portainer --> open homeassistant container --> open console --> typ: pip install --upgrade pip --> restart home assistant OS

Will your solution help with my error from the logs?

Logger: homeassistant.util.package
Source: util/package.py:107
First occurred: 18:08:39 (3 occurrences)
Last logged: 18:08:56

Unable to install package pyuptimekuma==0.0.6: ERROR: Cannot install pyuptimekuma==0.0.6 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts [notice] A new release of pip is available: 23.0 -> 23.0.1 [notice] To update, run: pip install --upgrade pip

**Comment by Sarnog** [comment] 2023-03-06 17:20
> > > Im running HAOS as a VM and Uptime Kuma on a Raspberry Pi3 with docker-compose. I jumped inside the container but no go.
> > > ```
> > > Collecting pyuptimekuma==0.0.6
> > >   Could not find a version that satisfies the requirement pyuptimekuma==0.0.6 (from versions: )
> > > No matching distribution found for pyuptimekuma==0.0.6
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Any advice is much appreciated.
> > > edit: clarification around my setup
> > 
> > Open portainer --> open homeassistant container --> open console --> typ: pip install --upgrade pip --> restart home assistant OS
> 
> Will your solution help with my error from the logs?
> 
> Logger: homeassistant.util.package
> Source: util/package.py:107
> First occurred: 18:08:39 (3 occurrences)
> Last logged: 18:08:56
> 
> Unable to install package pyuptimekuma==0.0.6: ERROR: Cannot install pyuptimekuma==0.0.6 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts [notice] A new release of pip is available: 23.0 -> 23.0.1 [notice] To update, run: pip install --upgrade pip
> 
> 

Yes, i had the same error. This fixed it for me...

**Comment by walkerfreeman** [comment] 2023-03-06 17:22
I'm the only one trying to integrate Uptime Kuma into HA....

**Comment by Sarnog** [comment] 2023-03-06 17:23
> I'm the only one trying to integrate Uptime Kuma into HA....

No, i use it as well and a lot of people do...

**Comment by walkerfreeman** [comment] 2023-03-06 17:31
Is there any other way to install this fix in HA because I can't find Portainer?

**Comment by Sarnog** [comment] 2023-03-06 17:36
> Is there any other way to install this fix in HA because I can't find Portainer?
> 

Go to settings --> add-on --> 3 dots in right corner --> add repo --> https://github.com/MaxWinterstein/homeassistant-addons/ paste this link --> clear browser cache. Now it's in the addon store

**Comment by walkerfreeman** [comment] 2023-03-06 17:49
So where is the possibility to run the update now?

![image](https://user-images.githubusercontent.com/122822100/223190283-b25d81e8-3841-454f-b826-e160cab975ef.png)

**Comment by Sarnog** [comment] 2023-03-06 17:52
> So where is the possibility to run the update now?
> 
> ![image](https://user-images.githubusercontent.com/122822100/223190283-b25d81e8-3841-454f-b826-e160cab975ef.png)
> 

Yes, go to containers --> homeassistant --> console --> typ: pip install --upgrade pip --> restart container

**Comment by walkerfreeman** [comment] 2023-03-06 18:00
But I don't have anything here
![image](https://user-images.githubusercontent.com/122822100/223192741-18b78b59-0bd4-4292-92de-365453ca981b.png)

**Comment by Sarnog** [comment] 2023-03-06 18:01
> But I don't have anything here
> ![image](https://user-images.githubusercontent.com/122822100/223192741-18b78b59-0bd4-4292-92de-365453ca981b.png)
> 

Are you using home assistant os?

**Comment by walkerfreeman** [comment] 2023-03-06 18:04
yes ha (rpi4)

**Comment by Sarnog** [comment] 2023-03-06 18:07
> yes ha (rpi4)
> 

And you're running the addon in home assistant on that raspberry pi?

**Comment by walkerfreeman** [comment] 2023-03-06 18:09
![image](https://user-images.githubusercontent.com/122822100/223194506-7a132eeb-73e0-4c0d-b27c-50940fba2921.png)

**Comment by Sarnog** [comment] 2023-03-06 18:29
> Maybe the problem is that I don't have Docker installed?

Should be if you installed home assistant container and after that supervised. Please check the info on the page in that link.

You can check if you go to terminal in home assistant (also an addon) typ:

docker ps

This should give you also a list of docker containers, or an error that docker isn't installed

**Comment by walkerfreeman** [comment] 2023-03-06 18:38
I installed HA from the image following these instructions
![image](https://user-images.githubusercontent.com/122822100/223200600-f9ab9526-68f2-426a-aea8-218d05b49eff.png)

**Comment by Sarnog** [comment] 2023-03-06 18:41
> I installed HA from the image following these instructions
> ![image](https://user-images.githubusercontent.com/122822100/223200600-f9ab9526-68f2-426a-aea8-218d05b49eff.png)
> 
> 

Also the second part for supervised?

**Comment by walkerfreeman** [comment] 2023-03-06 19:19
I don't understand the question

**Comment by Sarnog** [comment] 2023-03-06 20:23
> I don't understand the question
> 

If you check the site you just posted, there are instructions for installation of home assistant core, followed bij home assistant supervised. Check if you followed all steps.

You can also check docker containers in the terminal by typing:

Docker ps

**Comment by Heelderpeel** [comment] 2023-03-06 21:16
And for de HASSIO users, someone a solution?

**Comment by terriblefox** [comment] 2023-03-06 21:50
> And for de HASSIO users, someone a solution?

Works Hassio on RPI 4

**Comment by Sarnog** [comment] 2023-03-06 21:53
> And for de HASSIO users, someone a solution?

See my explaination...

**Comment by ChristopherGriffin** [comment] 2023-03-06 23:35
> Strange things happen, please take a look at this link. Maybe that helps:
> 
> https://community.home-assistant.io/t/cant-find-home-assistant-container-in-docker/183944

So I followed the instructions and it was very informative.  I performed the pip install --upgrade pip and it seemed to work.  
![image](https://user-images.githubusercontent.com/7265428/223280734-87d1dd59-d1a5-4e63-891e-1fc50821d86c.png)

However I still get the same error on uptime kuma integration after rebooting the server

![image](https://user-images.githubusercontent.com/7265428/223280928-7cc26280-b904-42ab-9da8-4946f9c7b1b0.png)

**Comment by phk-r** [comment] 2023-03-07 07:22
> > Strange things happen, please take a look at this link. Maybe that helps:
> > https://community.home-assistant.io/t/cant-find-home-assistant-container-in-docker/183944
> 
> So I followed the instructions and it was very informative. I performed the pip install --upgrade pip and it seemed to work. ![image](https://user-images.githubusercontent.com/7265428/223280734-87d1dd59-d1a5-4e63-891e-1fc50821d86c.png)
> 
> However I still get the same error on uptime kuma integration after rebooting the server
> 
> ![image](https://user-images.githubusercontent.com/7265428/223280928-7cc26280-b904-42ab-9da8-4946f9c7b1b0.png)

You also need to run the command for upgrading pyuptimekuma. Its further up this thread.

**Comment by Sarnog** [comment] 2023-03-07 10:11
> > Strange things happen, please take a look at this link. Maybe that helps:
> > 
> > https://community.home-assistant.io/t/cant-find-home-assistant-container-in-docker/183944
> 
> So I followed the instructions and it was very informative.  I performed the pip install --upgrade pip and it seemed to work.  
> ![image](https://user-images.githubusercontent.com/7265428/223280734-87d1dd59-d1a5-4e63-891e-1fc50821d86c.png)
> 
> However I still get the same error on uptime kuma integration after rebooting the server
> 
> ![image](https://user-images.githubusercontent.com/7265428/223280928-7cc26280-b904-42ab-9da8-4946f9c7b1b0.png)
> 

Try to remove and re-install the uptime kuma add-on. If that doesn't work, you need to install pyuptimekuma in the terminal as well (where you typed the pip command)

**Comment by VNRARA** [comment] 2023-03-07 17:43
> > > > > > 
> > > > > 
> > > > > 
> > > > > @danielsmith89 could you give some more details around that please, is that in the docker container, what was the command you ran ? as I tried pip3 install pyuptimekuma==0.0.6 didn't do anything....
> > > > > thanks
> > > > 
> > > > 
> > > > Yes, go inside the Home Assistant docker container (if that's what you are running HA in) and the issue that comand
> > > 
> > > 
> > > Thank you that worked.
> > 
> > 
> > @danielsmith89 I plonked that into the HA terminal (Ha OS via VMM) but it didn't work. It updated, but it didn't work.
> 
> The SSH terminal is an addon that runs inside its own container, you have to attach to homassistant docker (if you run "docker ps -a" you should see it running) and then you run the command to install pyuptimekuma... I installed portainer-agent on hassos in a docker so it is much easier to access and manage the dockers environment from outside the addon SSH terminal.

I have got no clue where to start to attach to docker or get into that part of HAOS on my VMM install. Only place I know is to connect to a terminal directly via VMM where the CMD shows ha > 

But from there I have no idea what commands to a to work inside the Home assistant container sorta say.

**Comment by hs82h** [comment] 2023-03-07 18:28
> > > > > > > 
> > > > > > 
> > > > > > 
> > > > > > @danielsmith89 could you give some more details around that please, is that in the docker container, what was the command you ran ? as I tried pip3 install pyuptimekuma==0.0.6 didn't do anything....
> > > > > > thanks
> > > > > 
> > > > > 
> > > > > Yes, go inside the Home Assistant docker container (if that's what you are running HA in) and the issue that comand
> > > > 
> > > > 
> > > > Thank you that worked.
> > > 
> > > 
> > > @danielsmith89 I plonked that into the HA terminal (Ha OS via VMM) but it didn't work. It updated, but it didn't work.
> > 
> > 
> > The SSH terminal is an addon that runs inside its own container, you have to attach to homassistant docker (if you run "docker ps -a" you should see it running) and then you run the command to install pyuptimekuma... I installed portainer-agent on hassos in a docker so it is much easier to access and manage the dockers environment from outside the addon SSH terminal.
> 
> I have got no clue where to start to attach to docker or get into that part of HAOS on my VMM install. Only place I know is to connect to a terminal directly via VMM where the CMD shows ha >
> 
> But from there I have no idea what commands to a to work inside the Home assistant container sorta say.

On your docker host type:
docker exec <containername> <command>

**Comment by Heelderpeel** [comment] 2023-03-07 21:05
> > And for de HASSIO users, someone a solution?
> 
> See my explaination...

oke thnx

**Comment by meichthys** [comment] 2023-03-09 04:52
This should now be patched in v2.1.0.
Please check HACS and report back if you have any issues.

**Comment by mvtslot** [comment] 2023-03-09 05:21
Yes, it works.  Thanks!

**Closed** 2023-03-09 11:54 UTC
Labels: bug

**Comment by Heelderpeel** [comment] 2023-03-09 17:17
works perfect, thnx.
